export interface ModelInfo {
  id: string;
  name: string;
  provider: string;
  lab: string;
  costInput: number;   // $ per million tokens
  costOutput: number;  // $ per million tokens
  contextWindow: number;
  description?: string;
}

export const TOP_50_MODELS: ModelInfo[] = [
  // 1. Mock Simulator (Offline Zero-Cost)
  {
    id: "mock/simulator",
    name: "Mock Simulator (Offline $0.00)",
    provider: "Local Mock",
    lab: "Local Mock",
    costInput: 0.0,
    costOutput: 0.0,
    contextWindow: 128000,
    description: "Zero-cost offline simulator for CI/CD test plumbing and prompt regressions.",
  },

  // 2-11. OpenAI
  {
    id: "openai/gpt-4o-mini",
    name: "OpenAI GPT-4o-mini",
    provider: "OpenAI",
    lab: "OpenAI",
    costInput: 0.15,
    costOutput: 0.6,
    contextWindow: 128000,
    description: "Affordable, fast intelligence for lightweight tasks and high-throughput evals.",
  },
  {
    id: "openai/gpt-4o",
    name: "OpenAI GPT-4o",
    provider: "OpenAI",
    lab: "OpenAI",
    costInput: 2.5,
    costOutput: 10.0,
    contextWindow: 128000,
    description: "Flagship multimodal frontier model with strong reasoning and coding capabilities.",
  },
  {
    id: "openai/gpt-4.1-mini",
    name: "OpenAI GPT-4.1-mini",
    provider: "OpenAI",
    lab: "OpenAI",
    costInput: 0.2,
    costOutput: 0.8,
    contextWindow: 200000,
    description: "Enhanced speed and instruction following with extended context support.",
  },
  {
    id: "openai/gpt-5.5",
    name: "OpenAI GPT-5.5",
    provider: "OpenAI",
    lab: "OpenAI",
    costInput: 3.0,
    costOutput: 12.0,
    contextWindow: 1050000,
    description: "Frontier GPT model for advanced software engineering and deep knowledge work.",
  },
  {
    id: "openai/o1",
    name: "OpenAI o1",
    provider: "OpenAI",
    lab: "OpenAI",
    costInput: 15.0,
    costOutput: 60.0,
    contextWindow: 200000,
    description: "Deep reasoning model trained with reinforcement learning for complex math and logic.",
  },
  {
    id: "openai/o1-mini",
    name: "OpenAI o1-mini",
    provider: "OpenAI",
    lab: "OpenAI",
    costInput: 3.0,
    costOutput: 12.0,
    contextWindow: 128000,
    description: "Fast reasoning model optimized for STEM, math, and code generation.",
  },
  {
    id: "openai/o3-mini",
    name: "OpenAI o3-mini",
    provider: "OpenAI",
    lab: "OpenAI",
    costInput: 1.1,
    costOutput: 4.4,
    contextWindow: 200000,
    description: "Next-generation high-efficiency reasoning model with configurable reasoning effort.",
  },
  {
    id: "openai/gpt-4-turbo",
    name: "OpenAI GPT-4 Turbo",
    provider: "OpenAI",
    lab: "OpenAI",
    costInput: 10.0,
    costOutput: 30.0,
    contextWindow: 128000,
    description: "General-purpose GPT-4 model with 128k context and Vision support.",
  },
  {
    id: "openai/gpt-3.5-turbo",
    name: "OpenAI GPT-3.5 Turbo",
    provider: "OpenAI",
    lab: "OpenAI",
    costInput: 0.5,
    costOutput: 1.5,
    contextWindow: 16385,
    description: "Legacy fast completion model for basic formatting and classification.",
  },

  // 12-18. Anthropic Claude
  {
    id: "anthropic/claude-3-5-sonnet",
    name: "Anthropic Claude 3.5 Sonnet",
    provider: "Anthropic",
    lab: "Anthropic",
    costInput: 3.0,
    costOutput: 15.0,
    contextWindow: 200000,
    description: "Industry-leading intelligence on coding, multi-step agent reasoning, and analysis.",
  },
  {
    id: "anthropic/claude-3-5-haiku",
    name: "Anthropic Claude 3.5 Haiku",
    provider: "Anthropic",
    lab: "Anthropic",
    costInput: 0.8,
    costOutput: 4.0,
    contextWindow: 200000,
    description: "Ultra-fast Claude model surpassing Claude 3 Opus on most standard benchmarks.",
  },
  {
    id: "anthropic/claude-3-opus",
    name: "Anthropic Claude 3 Opus",
    provider: "Anthropic",
    lab: "Anthropic",
    costInput: 15.0,
    costOutput: 75.0,
    contextWindow: 200000,
    description: "Deep analytical and nuanced prose generation for high-stakes evaluations.",
  },
  {
    id: "anthropic/claude-opus-4.7",
    name: "Anthropic Claude Opus 4.7",
    provider: "Anthropic",
    lab: "Anthropic",
    costInput: 12.0,
    costOutput: 60.0,
    contextWindow: 1000000,
    description: "Next-gen Opus tier with 1M context for complex architecture and repo refactoring.",
  },
  {
    id: "anthropic/claude-3-sonnet",
    name: "Anthropic Claude 3 Sonnet",
    provider: "Anthropic",
    lab: "Anthropic",
    costInput: 3.0,
    costOutput: 15.0,
    contextWindow: 200000,
    description: "Balanced performance and speed for enterprise workflows.",
  },
  {
    id: "anthropic/claude-3-haiku",
    name: "Anthropic Claude 3 Haiku",
    provider: "Anthropic",
    lab: "Anthropic",
    costInput: 0.25,
    costOutput: 1.25,
    contextWindow: 200000,
    description: "Compact Claude 3 tier for near-instant responses.",
  },

  // 19-24. Google Gemini
  {
    id: "google/gemini-2.0-flash",
    name: "Google Gemini 2.0 Flash",
    provider: "Google",
    lab: "Google",
    costInput: 0.1,
    costOutput: 0.4,
    contextWindow: 1048576,
    description: "Sub-second multimodal speed with 1M context and native tool calling.",
  },
  {
    id: "google/gemini-2.5-pro",
    name: "Google Gemini 2.5 Pro",
    provider: "Google",
    lab: "Google",
    costInput: 1.25,
    costOutput: 5.0,
    contextWindow: 2097152,
    description: "2M context frontier reasoning model for massive codebase comprehension.",
  },
  {
    id: "google/gemini-1.5-pro",
    name: "Google Gemini 1.5 Pro",
    provider: "Google",
    lab: "Google",
    costInput: 1.25,
    costOutput: 5.0,
    contextWindow: 2000000,
    description: "Long-context multimodal model for enterprise document and video analysis.",
  },
  {
    id: "google/gemini-1.5-flash",
    name: "Google Gemini 1.5 Flash",
    provider: "Google",
    lab: "Google",
    costInput: 0.075,
    costOutput: 0.3,
    contextWindow: 1000000,
    description: "High-frequency lightweight model optimized for low latency and high volume.",
  },
  {
    id: "google/gemini-3.5-flash",
    name: "Google Gemini 3.5 Flash",
    provider: "Google",
    lab: "Google",
    costInput: 0.12,
    costOutput: 0.45,
    contextWindow: 1000000,
    description: "Next-gen Flash tier with improved coding and structured outputs.",
  },

  // 25-30. DeepSeek
  {
    id: "deepseek/deepseek-v4-pro-0813",
    name: "DeepSeek v4 Pro",
    provider: "DeepSeek",
    lab: "DeepSeek",
    costInput: 0.14,
    costOutput: 0.28,
    contextWindow: 1000000,
    description: "Million-token MoE flagship with hybrid thinking and non-thinking modes.",
  },
  {
    id: "deepseek/deepseek-v4-flash",
    name: "DeepSeek v4 Flash",
    provider: "DeepSeek",
    lab: "DeepSeek",
    costInput: 0.07,
    costOutput: 0.14,
    contextWindow: 1048576,
    description: "Economical high-speed DeepSeek model for agent workflows.",
  },
  {
    id: "deepseek/deepseek-r1",
    name: "DeepSeek R1",
    provider: "DeepSeek",
    lab: "DeepSeek",
    costInput: 0.55,
    costOutput: 2.19,
    contextWindow: 128000,
    description: "Open reasoning model rivaling OpenAI o1 on math, coding, and logical tasks.",
  },
  {
    id: "deepseek/deepseek-chat",
    name: "DeepSeek V3 (Chat)",
    provider: "DeepSeek",
    lab: "DeepSeek",
    costInput: 0.14,
    costOutput: 0.28,
    contextWindow: 64000,
    description: "671B MoE model delivering frontier intelligence at ultra-low inference cost.",
  },
  {
    id: "deepseek/deepseek-coder",
    name: "DeepSeek Coder V2.5",
    provider: "DeepSeek",
    lab: "DeepSeek",
    costInput: 0.14,
    costOutput: 0.28,
    contextWindow: 128000,
    description: "Specialized code generation and repository synthesis model.",
  },

  // 31-36. Meta Llama
  {
    id: "meta/llama-3.3-70b-instruct",
    name: "Meta Llama 3.3 70B",
    provider: "Meta",
    lab: "Meta",
    costInput: 0.4,
    costOutput: 0.8,
    contextWindow: 128000,
    description: "Top-tier open-weight model delivering 405B-class capability in a 70B footprint.",
  },
  {
    id: "meta/llama-3.1-405b-instruct",
    name: "Meta Llama 3.1 405B",
    provider: "Meta",
    lab: "Meta",
    costInput: 2.5,
    costOutput: 5.0,
    contextWindow: 128000,
    description: "Massive 405B parameter open frontier model for synthetic data and complex eval.",
  },
  {
    id: "meta/llama-3.1-70b-instruct",
    name: "Meta Llama 3.1 70B",
    provider: "Meta",
    lab: "Meta",
    costInput: 0.5,
    costOutput: 0.9,
    contextWindow: 128000,
    description: "Highly capable open model for tool calling, reasoning, and summarization.",
  },
  {
    id: "meta/llama-3.1-8b-instruct",
    name: "Meta Llama 3.1 8B",
    provider: "Meta",
    lab: "Meta",
    costInput: 0.05,
    costOutput: 0.08,
    contextWindow: 128000,
    description: "Ultra-fast, low-memory 8B model suitable for real-time edge processing.",
  },
  {
    id: "meta/llama-3.2-3b-instruct",
    name: "Meta Llama 3.2 3B",
    provider: "Meta",
    lab: "Meta",
    costInput: 0.03,
    costOutput: 0.06,
    contextWindow: 128000,
    description: "Lightweight edge model for fast classification and routing.",
  },
  {
    id: "meta/llama-3.2-11b-vision",
    name: "Meta Llama 3.2 11B Vision",
    provider: "Meta",
    lab: "Meta",
    costInput: 0.16,
    costOutput: 0.2,
    contextWindow: 128000,
    description: "Multimodal Llama model with native document, image, and visual question answering.",
  },

  // 37-42. Mistral AI
  {
    id: "mistral/mistral-large",
    name: "Mistral Large 2",
    provider: "Mistral AI",
    lab: "Mistral AI",
    costInput: 2.0,
    costOutput: 6.0,
    contextWindow: 128000,
    description: "Flagship multilingual reasoning and code synthesis model with 123B parameters.",
  },
  {
    id: "mistral/mistral-small",
    name: "Mistral Small 3",
    provider: "Mistral AI",
    lab: "Mistral AI",
    costInput: 0.2,
    costOutput: 0.6,
    contextWindow: 128000,
    description: "Fast, cost-efficient 24B model with sub-second response times.",
  },
  {
    id: "mistral/codestral",
    name: "Mistral Codestral",
    provider: "Mistral AI",
    lab: "Mistral AI",
    costInput: 0.3,
    costOutput: 0.9,
    contextWindow: 256000,
    description: "Dedicated coding model fluent in 80+ programming languages with fill-in-the-middle.",
  },
  {
    id: "mistral/pixtral-large",
    name: "Mistral Pixtral Large",
    provider: "Mistral AI",
    lab: "Mistral AI",
    costInput: 2.0,
    costOutput: 6.0,
    contextWindow: 128000,
    description: "Multimodal frontier model for complex diagrams, documents, and visual reasoning.",
  },
  {
    id: "mistral/mixtral-8x22b",
    name: "Mixtral 8x22B",
    provider: "Mistral AI",
    lab: "Mistral AI",
    costInput: 0.9,
    costOutput: 2.7,
    contextWindow: 64000,
    description: "High-performance sparse mixture-of-experts model for math and reasoning.",
  },
  {
    id: "mistral/mixtral-8x7b",
    name: "Mixtral 8x7B",
    provider: "Mistral AI",
    lab: "Mistral AI",
    costInput: 0.24,
    costOutput: 0.24,
    contextWindow: 32768,
    description: "Classic high-throughput open MoE model.",
  },

  // 43-46. Alibaba Qwen
  {
    id: "alibaba/qwen3.8-flash",
    name: "Alibaba Qwen 3.8 Flash",
    provider: "Alibaba",
    lab: "Alibaba",
    costInput: 0.12,
    costOutput: 0.4,
    contextWindow: 1000000,
    description: "1M context vision-language model for visual reasoning and agent tasks.",
  },
  {
    id: "alibaba/qwen3.8-27b",
    name: "Alibaba Qwen 3.8 27B",
    provider: "Alibaba",
    lab: "Alibaba",
    costInput: 0.2,
    costOutput: 0.6,
    contextWindow: 131072,
    description: "Dense 27B vision-language model with strong coding and math benchmark scores.",
  },
  {
    id: "alibaba/qwen-2.5-72b-instruct",
    name: "Alibaba Qwen 2.5 72B",
    provider: "Alibaba",
    lab: "Alibaba",
    costInput: 0.35,
    costOutput: 0.7,
    contextWindow: 128000,
    description: "Flagship 72B open model with state-of-the-art coding and knowledge retrieval.",
  },
  {
    id: "alibaba/qwen-2.5-coder-32b",
    name: "Alibaba Qwen 2.5 Coder 32B",
    provider: "Alibaba",
    lab: "Alibaba",
    costInput: 0.18,
    costOutput: 0.36,
    contextWindow: 128000,
    description: "Specialized 32B coding model competitive with proprietary frontier models.",
  },

  // 47-48. xAI Grok
  {
    id: "xai/grok-2",
    name: "xAI Grok 2",
    provider: "xAI",
    lab: "xAI",
    costInput: 2.0,
    costOutput: 10.0,
    contextWindow: 128000,
    description: "Advanced frontier intelligence with real-time knowledge synthesis and vision.",
  },
  {
    id: "xai/grok-2-vision",
    name: "xAI Grok 2 Vision",
    provider: "xAI",
    lab: "xAI",
    costInput: 2.0,
    costOutput: 10.0,
    contextWindow: 128000,
    description: "Multimodal Grok model for visual reasoning and document processing.",
  },

  // 49-50. Additional Labs (Cohere, Moonshot, Zhipu, MiniMax)
  {
    id: "cohere/command-r-plus",
    name: "Cohere Command R+",
    provider: "Cohere",
    lab: "Cohere",
    costInput: 2.5,
    costOutput: 10.0,
    contextWindow: 128000,
    description: "Enterprise RAG-optimized model with high precision citations and tool calling.",
  },
  {
    id: "moonshotai/kimi-k2.7-code",
    name: "Moonshot Kimi K2.7 Code",
    provider: "Moonshot AI",
    lab: "Moonshot AI",
    costInput: 0.5,
    costOutput: 1.5,
    contextWindow: 256000,
    description: "Coding-focused Kimi model for long-horizon repository engineering.",
  },
  {
    id: "zhipuai/glm-5.3-flash",
    name: "Zhipu GLM-5.3 Flash",
    provider: "Zhipu AI",
    lab: "Zhipu AI",
    costInput: 0.1,
    costOutput: 0.2,
    contextWindow: 1000000,
    description: "Multimodal GLM model for coding, document parsing, and agent tasks.",
  },
  {
    id: "minimax/minimax-m2.5",
    name: "MiniMax M2.5",
    provider: "MiniMax",
    lab: "MiniMax",
    costInput: 0.2,
    costOutput: 0.6,
    contextWindow: 196000,
    description: "Prior MiniMax model for agent workflows, office edits, and automation.",
  },
];

export const ALL_MODELS = TOP_50_MODELS;

export const MODEL_MAP = new Map<string, ModelInfo>(
  TOP_50_MODELS.map((m) => [m.id, m])
);

export function getModelPricing(modelId: string): { input: number; output: number } {
  const found = MODEL_MAP.get(modelId);
  if (found) {
    return { input: found.costInput, output: found.costOutput };
  }
  if (modelId.startsWith("mock/")) return { input: 0.0, output: 0.0 };
  if (modelId.includes("mini") || modelId.includes("flash") || modelId.includes("8b")) {
    return { input: 0.15, output: 0.6 };
  }
  return { input: 2.0, output: 8.0 };
}
